name = "quran-reciters-encyclopedia"
pages_build_output_dir = ".open-next/worker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Force Pages to use this build command
[build]
command = "npm run cloudflare:build"
